
services:
  tinygo:
    image: tinygo/tinygo:latest
    restart: always
    privileged: true
    volumes:
      - "./:/usr/src/app"
    working_dir: /usr/src/app
    command: ["tail", "-f", "/dev/null"]