version: '3'

services:
  tinygo:
    image: tinygo/tinygo:0.35.0
    restart: always
    privileged: true
    volumes:
      - "./:/usr/src/app"
    working_dir: /usr/src/app
    command: ["tail", "-f", "/dev/null"]