
services:
  tinygo:
    image: tinygo/tinygo:latest
    restart: always
    privileged: true
    user: root
    volumes:
      - "./:/usr/src/app"
      - "/dev/ttyACM0:/dev/ttyACM0"
      # - "/dev/ttyAMA10:/dev/ttyAMA10"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      # - "/media/romelcampbell/RPI-RP21:/mnt/RPI-RP2"
    working_dir: /usr/src/app
    command: ["tail", "-f", "/dev/null"]
