version: '3'

services:
  prometheus:
    image: quay.io/prometheus/prometheus:v2.45.0
    restart: always
    volumes:
      - "prom_data:/prometheus"
      - "./prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    ports:
      - "9090:9090"
    networks:
      - prom_net
    extra_hosts:
      - "rpi-hosts:192.168.38.1"
  node:
    image: quay.io/prometheus/node-exporter:v1.6.1
    command:
      - "--path.rootfs=/host"
    pid: host
    restart: always
    volumes:
      - "/:/host:ro,rslave"
    expose:
      - "9100"
    network_mode: host 

volumes:
  prom_data: {}

networks:
  prom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.39.0/24
          gateway: 192.168.38.1

    