---
global:
  scrape_interval: 15s 
  scrape_timeout: 10s
  evaluation_interval: 15s 
alerting:
  alertmanagers:
    - follow_redirects: true
      enable_http2: true
      scheme: http
      timeout: 
      api_version: v2
    - static_configs:
        - targets: []
scrape_configs:
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]